export const employeeData=[
  {
    "EmployeeID": "ADW001",
    "FirstName": "Yusuf",
    "LastName": "Kolawole",
    "Sex": "Male",
    "Age": 25,
    "Position": "Software Developer",
    "Department": "ICT",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW002",
    "FirstName": "Amina",
    "LastName": "Abdul",
    "Sex": "Female",
    "Age": 28,
    "Position": "Data Analyst",
    "Department": "Analytics",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW003",
    "FirstName": "John",
    "LastName": "Doe",
    "Sex": "Male",
    "Age": 30,
    "Position": "Project Manager",
    "Department": "Project Management",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":2
  },
  {
    "EmployeeID": "ADW004",
    "FirstName": "Emily",
    "LastName": "Smith",
    "Sex": "Female",
    "Age": 22,
    "Position": "Intern",
    "Department": "HR",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW005",
    "FirstName": "Ahmed",
    "LastName": "Ali",
    "Sex": "Male",
    "Age": 35,
    "Position": "System Administrator",
    "Department": "IT",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":3
  },
  {
    "EmployeeID": "ADW006",
    "FirstName": "Jane",
    "LastName": "Doe",
    "Sex": "Female",
    "Age": 27,
    "Position": "Database Administrator",
    "Department": "IT",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":3
  },
  {
    "EmployeeID": "ADW007",
    "FirstName": "David",
    "LastName": "Williams",
    "Sex": "Male",
    "Age": 32,
    "Position": "Financial Analyst",
    "Department": "Finance",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":2
  },
  {
    "EmployeeID": "ADW008",
    "FirstName": "Zainab",
    "LastName": "Mohammed",
    "Sex": "Female",
    "Age": 29,
    "Position": "Marketing Specialist",
    "Department": "Marketing",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW009",
    "FirstName": "Michael",
    "LastName": "Johnson",
    "Sex": "Male",
    "Age": 26,
    "Position": "Customer Support Representative",
    "Department": "Customer Service",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW010",
    "FirstName": "Fatemeh",
    "LastName": "Rahmani",
    "Sex": "Female",
    "Age": 31,
    "Position": "Research Scientist",
    "Department": "Research and Development",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW011",
    "FirstName": "Alex",
    "LastName": "Turner",
    "Sex": "Male",
    "Age": 23,
    "Position": "Software Engineer",
    "Department": "Engineering",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW012",
    "FirstName": "Sophia",
    "LastName": "Lee",
    "Sex": "Female",
    "Age": 24,
    "Position": "UX/UI Designer",
    "Department": "Design",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW013",
    "FirstName": "Daniel",
    "LastName": "Nguyen",
    "Sex": "Male",
    "Age": 28,
    "Position": "Product Manager",
    "Department": "Product Management",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW014",
    "FirstName": "Ella",
    "LastName": "White",
    "Sex": "Female",
    "Age": 25,
    "Position": "Sales Representative",
    "Department": "Sales",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW015",
    "FirstName": "Ryan",
    "LastName": "Clark",
    "Sex": "Male",
    "Age": 33,
    "Position": "Human Resources Manager",
    "Department": "HR",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":5
  },
  {
    "EmployeeID": "ADW016",
    "FirstName": "Olivia",
    "LastName": "Martin",
    "Sex": "Female",
    "Age": 30,
    "Position": "Quality Assurance Specialist",
    "Department": "QA",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW017",
    "FirstName": "Isaac",
    "LastName": "Taylor",
    "Sex": "Male",
    "Age": 29,
    "Position": "Network Engineer",
    "Department": "IT",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW018",
    "FirstName": "Eva",
    "LastName": "Yang",
    "Sex": "Female",
    "Age": 26,
    "Position": "Content Writer",
    "Department": "Marketing",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":2
  },
  {
    "EmployeeID": "ADW019",
    "FirstName": "Nathan",
    "LastName": "Robinson",
    "Sex": "Male",
    "Age": 27,
    "Position": "Business Analyst",
    "Department": "Business Analysis",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":4
  },
  {
    "EmployeeID": "ADW020",
    "FirstName": "Sophie",
    "LastName": "Gomez",
    "Sex": "Female",
    "Age": 24,
    "Position": "UI Developer",
    "Department": "Engineering",
    "QualityOfWork": 5,
    "Productivity": 4,
    "Efficiency": 3,
    "GoalAchievement": 4,
    "TeamWork": 5,
    "ProblemSolving": 4,
    "Punctuality": 2,
    "Ethics": 5,
    "kPI":3
  }
]
